name: release.yml
on:
  release:
    types: [published,updated]
  workflow_dispatch:
   inputs:
    enableManualDeployement :
      description: 'Click to enable manual deployment from a custom branch to the test environment.'
      default: false
      required: true
      type: boolean    
jobs:
  publish:    
    name: publish
    runs-on: ubuntu-latest
    steps:        
    - name: Echo
      if: github.event_name == 'release' && github.event.action == 'created'
      run: echo "Started"
