name: release.yml
on:
  release:
    types: [created]
jobs:
  publish:    
    name: publish
    runs-on: ubuntu-latest
    steps:        
    - name: Echo
      if: github.event_name == 'release' && github.event.action == 'created'
      run: echo "Started"
