name: pack.nuget.yml
on:
  push:
    tags:
      - '*'

  #workflow_dispatch:
  # inputs:
  #  enableManualDeployement :
  #    description: 'Click to enable manual deployment from a custom branch to the test environment.'
  #    default: false
  #    required: true
  #    type: boolean

jobs:
  publish:
    env:
      solution: '${{ github.workspace }}/nucelotidz.storage.queue.sln'
      feedurl : 'https://nuget.pkg.github.com/nucleo-tidz/index.json'
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Set version variable from tag
      run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV    

    - name: Restore dependencies
      run: dotnet restore $solution

    - name: Build
      run: dotnet build $solution /p:Version=${version} --no-restore

    #- name: Publish      
     # run: nuget push **\*.${version}.nupkg -Source $feedurl  -SkipDuplicate -ApiKey ${{ secrets.GITHUB_TOKEN }}
