name: pack.nuget.yml
on:
  push:
    branches:
      - main

  workflow_dispatch:
   inputs:
    enableManualDeployement :
      description: 'Click to enable manual deployment from a custom branch to the test environment.'
      default: false
      required: true
      type: boolean

jobs:
  publish:
    env:
      solution: '${{ github.workspace }}/src/nucelotidz.storage.queue.sln'
      feedurl : 'https://nuget.pkg.github.com/nucleo-tidz/index.json'
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore $solution

    - name: Build
      run: dotnet build $solution --no-restore

    - name: Publish      
      run: nuget push **\*.nupkg -Source $feedurl  -SkipDuplicate -ApiKey ${{secrets.NUGET_TOKEN}}